project_id = "nncqqbzgercubtzlunyl"

[functions.create-consultant]
verify_jwt = false

[functions.create-admin]
verify_jwt = false

[functions.manage-user]
verify_jwt = false

[functions.gcal-oauth]
verify_jwt = false

[functions.gcal-sync-booking]
verify_jwt = false

[functions.gcal-webhook]
verify_jwt = false
