import {EditorialCover} from '@/components/editorial-cover';
import {notFound} from 'next/navigation';
import {readGuides} from '@/lib/content-server';
import {ManagedImage} from '@/components/managed-image';
import {guideDepth} from '@/lib/guide-depth';
import {SiteHeader,SiteFooter} from '@/components/site-header';
export async function generateMetadata({params}:{params:Promise<{id:string}>}){const guides=await readGuides();const {id}=await params;const g=guides.find(x=>x.id===id);return {title:g?g.title+'｜步步搬家':'搬家知識',description:g?.summary}}
export default async function Guide({params}:{params:Promise<{id:string}>}){
 const guides=await readGuides();const {id}=await params;const g=guides.find(x=>x.id===id);if(!g)notFound();const depth=g.managed?undefined:guideDepth[g.id];
 const sections:[string,string[]][]=[...g.items.map(([title,body]):[string,string[]]=>[title,[body]]),...(depth?.sections||[])];
 const readingMinutes=Math.max(3,Math.ceil((g.items.map(x=>x.join('')).join('').length+(depth?JSON.stringify(depth).length:0))/450));
 const related=guides.filter(x=>x.id!==id).sort((a,b)=>Number(b.label===g.label)-Number(a.label===g.label)).slice(0,3);
 return <><SiteHeader/><main className="knowledge-article wrap"><header><a className="breadcrumb" href="/guides">← 所有搬家知識</a><span className="kicker">{g.label} / BU BU NOTES</span><h1>{g.title}</h1><p>{g.summary}</p><span className="article-byline">步步編輯筆記 · 約 {readingMinutes} 分鐘閱讀 · 含準備清單與常見問題</span></header><div className="article-topic-cover"><ManagedImage src={g.image} alt={g.title} style={{width:'100%',maxHeight:480,objectFit:'cover'}}/></div><div className="article-layout"><aside><strong>這篇會聊到</strong>{sections.map(([t],i)=><a href={'#part-'+i} key={t}>{String(i+1).padStart(2,'0')}　{t}</a>)}{depth&&<><a href="#example">情境示例</a><a href="#checklist">實用核對清單</a><a href="#questions">常見問題</a></>}</aside><div className="article-prose">{depth&&<div className="guide-introduction"><p>{depth.intro}</p><a href="#checklist">準備開始了？直接看核對清單 ↓</a></div>}{sections.map(([t,paragraphs],i)=><section id={'part-'+i} key={t}><span className="kicker">{String(i+1).padStart(2,'0')}</span><h2>{t}</h2>{paragraphs.map((p,n)=><p key={n} style={{whiteSpace:'pre-wrap'}}>{p}</p>)}</section>)}{depth&&<><section id="example" className="guide-example"><span className="kicker">PUT IT INTO PRACTICE</span><h2>{depth.example.title}</h2><p>{depth.example.text}</p><small>以上為準備方式示例，非實際客戶案例。</small></section><section id="checklist" className="guide-checklist"><span className="kicker">YOUR CHECKLIST</span><h2>做完這幾項，再往下一步。</h2><p>可以將這份清單存進備忘錄，和家人或服務窗口一起核對。</p><ul>{depth.checklist.map(item=><li key={item}><span aria-hidden="true">✓</span>{item}</li>)}</ul></section><section id="questions" className="guide-questions"><span className="kicker">GOOD TO KNOW</span><h2>你可能還想問</h2>{depth.faq.map(([question,answer])=><div key={question}><h3>{question}</h3><p>{answer}</p></div>)}</section></>}<div className="article-action"><h2>需要人一起安排？</h2><p>把地點、日期與需求告訴步步，細節一起確認。</p><a className="primary" href="/inquiry">預約估價 ↗</a></div></div></div><section className="related-reading"><span className="kicker">KEEP EXPLORING</span><h2>下一篇，也許剛好用得上。</h2>{related.map(x=><a href={'/guides/'+x.id} key={x.id}><span>{x.label}</span><strong>{x.title}</strong><span>↗</span></a>)}</section></main><SiteFooter/></>}
