import {createRequire} from 'node:module';import {readFileSync,readdirSync} from 'node:fs';import {pathToFileURL} from 'node:url';import {DatabaseSync} from 'node:sqlite';import assert from 'node:assert/strict';
const root=new URL('../',import.meta.url).pathname,require=createRequire(root+'package.json'),ts=require('typescript');
const db=new DatabaseSync(':memory:');for(const f of readdirSync(root+'drizzle').filter(f=>f.endsWith('.sql')))db.exec(readFileSync(root+'drizzle/'+f,'utf8'));
class Stmt{constructor(sql,args=[]){this.sql=sql;this.args=args}bind(...args){return new Stmt(this.sql,args)}async first(){return db.prepare(this.sql).get(...this.args)||null}async all(){return {results:db.prepare(this.sql).all(...this.args)}}async run(){const r=db.prepare(this.sql).run(...this.args);return {meta:{changes:Number(r.changes)}}}}
globalThis.testEnv={BUBU_ADMIN_EMAILS:'admin@test.invalid',DB:{prepare:sql=>new Stmt(sql),batch:async statements=>{db.exec('BEGIN');try{const result=[];for(const s of statements)result.push(/^SELECT/i.test(s.sql)?await s.all():await s.run());db.exec('COMMIT');return result}catch(e){db.exec('ROLLBACK');throw e}}}};
globalThis.testUser={userId:'test-admin',email:'admin@test.invalid'};
const cache={};function module(file){if(cache[file])return cache[file];let source=readFileSync(root+file,'utf8');if(file==='lib/media-server.ts')source=source.replace("import {env} from 'cloudflare:workers';",'const env=globalThis.testEnv;');if(file==='lib/server.ts')source=source.replace("import {env} from 'cloudflare:workers';",'const env=globalThis.testEnv;').replace("import {getChatGPTUser} from '@/app/chatgpt-auth';",'const getChatGPTUser=async()=>globalThis.testUser;');source=source.replace(/from ['"]([^'"]+)['"]/g,(full,name)=>{if(name==='zod')return 'from '+JSON.stringify(pathToFileURL(require.resolve('zod')).href);if(name.startsWith('@/'))return 'from '+JSON.stringify(module(name.slice(2)+'.ts'));if(name.startsWith('./'))return 'from '+JSON.stringify(module('lib/'+name.slice(2)+'.ts'));return full});const js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;return cache[file]='data:text/javascript;base64,'+Buffer.from(js).toString('base64')}
const objects=new Map();globalThis.testEnv.MEDIA={put:async(id,bytes,options)=>{objects.set(id,{body:bytes,httpMetadata:options.httpMetadata,httpEtag:'"test"'})},get:async id=>objects.get(id)||null,delete:async id=>objects.delete(id)};
const uploads=await import(module('app/api/admin/media/route.ts')),photos=await import(module('app/api/admin/photos/route.ts')),serve=await import(module('app/api/media/[id]/route.ts'));
const post=data=>new Request('https://test.invalid/api/admin/photos',{method:'POST',headers:{origin:'https://test.invalid'},body:JSON.stringify(data)});
const upload=(body,type='image/png')=>new Request('https://test.invalid/api/admin/media',{method:'POST',headers:{origin:'https://test.invalid','Content-Type':type},body});
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=','base64');
assert.equal((await uploads.POST(upload('invalid'))).status,422);assert.equal((await uploads.POST(upload(png,'image/svg+xml'))).status,422);assert.equal((await uploads.POST(upload(new Uint8Array(5*1024*1024+1)))).status,413);
let r=await uploads.POST(upload(png));assert.equal(r.status,200);const {url}=await r.json(),id=url.split('/').pop();assert.equal(objects.size,1);assert.equal(db.prepare('SELECT count(*) n FROM media_assets').get().n,1);
const item={source:'/brand/hero-logo.png',assetId:id,alt:'步步搬家團隊',version:0};r=await photos.POST(post(item));assert.equal(r.status,200);assert.equal((await r.json()).photo.version,1);assert.equal((await photos.POST(post(item))).status,409);assert.equal((await photos.POST(post({...item,source:'/unauthorized.jpg'}))).status,422);assert.equal((await photos.POST(post({...item,assetId:crypto.randomUUID(),version:1}))).status,422);
r=await serve.GET(null,{params:Promise.resolve({id})});assert.equal(r.status,200);assert.equal(r.headers.get('Content-Type'),'image/png');assert.deepEqual(Buffer.from(await r.arrayBuffer()),png);assert.equal((await serve.GET(null,{params:Promise.resolve({id:'invalid'})})).status,404);
r=await photos.POST(post({...item,assetId:null,version:1}));assert.equal(r.status,200);assert.equal(db.prepare('SELECT asset_id FROM site_photos').get().asset_id,null);assert.equal(objects.size,1);
globalThis.testUser=null;assert.equal((await uploads.POST(upload(png))).status,403);assert.equal((await photos.POST(post(item))).status,403);assert.equal((await photos.GET()).status,403);assert.equal((await uploads.POST(new Request('https://test.invalid',{method:'POST',body:png}))).status,403);
console.log('PASS: upload/persist/serve, file type/size rejection, authorized slots, stale-write rejection, restore-original, admin access, same-origin protection.');
