import assert from 'node:assert/strict';import {module,db} from './pg-harness.mjs';
const admin=await import(module('app/api/admin/quotes/route.ts')),customer=await import(module('app/api/quote/[token]/route.ts')),callback=await import(module('app/api/payments/ecpay/route.ts')),ecpay=await import(module('lib/ecpay.ts')),pricing=await import(module('lib/material-order.ts'));
const req=(data)=>new Request('https://test.invalid/api/test',{method:'POST',headers:{origin:'https://test.invalid','Content-Type':'application/json'},body:JSON.stringify(data)});
const content={name:'Test customer',phone:'0912345678',date:'2026-12-01',validUntil:'2099-12-31',notes:'Testing',lines:[{category:'搬運',name:'一條龍搬運',spec:'',unit:'車',quantity:1,unitPrice:4200},{category:'打包',name:'打包',spec:'',unit:'人',quantity:2,unitPrice:800},...pricing.priceMaterials([{id:'2',quantity:10}])]};
assert.equal(pricing.priceMaterials([{id:'76',quantity:2}])[0].unitPrice,250);assert.equal(pricing.materialSelectionSchema.safeParse([{id:'2',quantity:1},{id:'2',quantity:2}]).success,false);
const vector=Object.fromEntries(new URLSearchParams('TradeDesc=促銷方案&PaymentType=aio&MerchantTradeDate=2023/03/12 15:30:23&MerchantTradeNo=ecpay20230312153023&MerchantID=3002607&ReturnURL=https://www.ecpay.com.tw/receive.php&ItemName=Apple iphone 15&TotalAmount=30000&ChoosePayment=ALL&EncryptType=1'));
assert.equal(await ecpay.checkMac(vector,'pwFHCqoQZGmho4w6','EkRm7iFT261dpevs'),'6C51C9E6888DE861FD62FB1DD17029FC742634498FD813DC43D4243B5685B840');
let r=await admin.POST(req({id:crypto.randomUUID(),version:0,action:'save',content:{...content,lines:[{...content.lines[0],quantity:-1}]}}));assert.equal(r.status,422);
const id=crypto.randomUUID();r=await admin.POST(req({id,version:0,action:'save',content,total:1}));assert.equal(r.status,200);let q=(await r.json()).quote;assert.equal(q.total,6350);assert.equal(q.version,1);const ctx={params:Promise.resolve({token:q.token})};assert.equal((await customer.GET(null,ctx)).status,404);
r=await admin.POST(req({id,version:1,action:'issue',content:JSON.parse(q.content)}));assert.equal(r.status,200);q=(await r.json()).quote;assert.equal(q.status,'issued');assert.equal((await admin.POST(req({id,version:q.version,action:'save',content}))).status,409);
assert.equal((await customer.POST(req({action:'accept',version:1}),ctx)).status,409);assert.equal((await customer.POST(req({action:'accept',version:q.version}),ctx)).status,200);assert.equal((await customer.POST(req({action:'checkout'}),ctx)).status,503);
Object.assign(globalThis.testEnv,{ECPAY_ENABLED:'true',ECPAY_MODE:'test',ECPAY_MERCHANT_ID:'3002607',ECPAY_HASH_KEY:'pwFHCqoQZGmho4w6',ECPAY_HASH_IV:'EkRm7iFT261dpevs',PAYMENT_PUBLIC_ORIGIN:'https://test.invalid',ECPAY_CALLBACK_READY:'true'});
r=await customer.POST(req({action:'checkout',amount:1}),ctx);assert.equal(r.status,200);const checkout=await r.json();assert.equal(checkout.fields.TotalAmount,'6350');assert.equal(checkout.fields.ChoosePayment,'Credit');assert.equal(checkout.endpoint,'https://payment-stage.ecpay.com.tw/Cashier/AioCheckOut/V5');const again=await (await customer.POST(req({action:'checkout'}),ctx)).json();assert.equal(checkout.fields.MerchantTradeNo,again.fields.MerchantTradeNo);assert.equal((await db.prepare('SELECT count(*) n FROM payments').bind().first()).n,1);
q=(await db.prepare('SELECT * FROM quotes WHERE id=?').bind(id).first());assert.equal((await admin.POST(req({id,version:q.version,action:'void',content:JSON.parse(q.content)}))).status,409);
let f={MerchantID:'3002607',MerchantTradeNo:checkout.fields.MerchantTradeNo,TradeAmt:'6350',TradeNo:'GATEWAY123',RtnCode:'1',RtnMsg:'success',SimulatePaid:'0'};
async function notify(fields,sign=true){const next={...fields};if(sign)next.CheckMacValue=await ecpay.checkMac(next,globalThis.testEnv.ECPAY_HASH_KEY,globalThis.testEnv.ECPAY_HASH_IV);return callback.POST(new Request('https://test.invalid/api/payments/ecpay',{method:'POST',body:new URLSearchParams(next)}))}
assert.equal((await notify({...f,TradeAmt:'1'})).status,400);assert.equal((await notify({...f,CheckMacValue:'0'.repeat(64)},false)).status,400);assert.equal((await notify({...f,SimulatePaid:'1'})).status,200);assert.equal((await db.prepare('SELECT status FROM payments').bind().first()).status,'simulated');assert.equal((await notify(f)).status,200);assert.equal((await db.prepare('SELECT status FROM payments').bind().first()).status,'test_paid');const auditCount=(await db.prepare('SELECT count(*) n FROM audit_log').bind().first()).n;assert.equal(await (await notify(f)).text(),'1|OK');assert.equal((await db.prepare('SELECT count(*) n FROM audit_log').bind().first()).n,auditCount);await notify({...f,RtnCode:'0'});assert.equal((await db.prepare('SELECT status FROM payments').bind().first()).status,'test_paid');assert.equal((await customer.POST(req({action:'checkout'}),ctx)).status,409);
// Exercise production classification locally without contacting any gateway.
globalThis.testEnv.ECPAY_MODE='live';globalThis.testEnv.ECPAY_MERCHANT_ID='1234567';
(await db.prepare("UPDATE payments SET mode='live',merchant_id='1234567',status='pending',paid_at=NULL").bind().run());f={...f,MerchantID:'1234567'};
await notify({...f,SimulatePaid:'1'});assert.equal((await db.prepare('SELECT status FROM payments').bind().first()).status,'simulated');
await notify(f);assert.equal((await db.prepare('SELECT status FROM payments').bind().first()).status,'succeeded');
await notify({...f,RtnCode:'0'});assert.equal((await db.prepare('SELECT status FROM payments').bind().first()).status,'succeeded');
globalThis.testUser=null;assert.equal((await admin.GET(new Request('https://test.invalid/api/admin/quotes'))).status,403);assert.equal((await admin.POST(req({}))).status,403);assert.equal((await customer.POST(new Request('https://test.invalid',{method:'POST',body:'{}'}),ctx)).status,403);
console.log('PASS: catalog snapshots; official ECPay SHA256 vector; server totals; immutable issued quote; stale confirmation; disabled checkout; persisted single checkout; amount/signature rejection; simulated/test payment isolation; duplicate callback idempotency; paid-state protection; admin authorization and CSRF.');
