import assert from 'node:assert/strict';import {module,db} from './pg-harness.mjs';
const reviews=await import(module('app/api/admin/reviews/route.ts'));
const req=data=>new Request('https://test.invalid/api/admin/reviews',{method:'POST',headers:{origin:'https://test.invalid'},body:JSON.stringify(data)});
const item={id:crypto.randomUUID(),version:0,name:'測試客戶',service:'一條龍搬家',date:'2026-01-01',text:'這是一筆僅供測試的回饋。',source:'服務問卷',sourceUrl:'',rating:5,verified:false,consent:false,published:false,sortOrder:10};
globalThis.testUser=null;assert.equal((await reviews.GET()).status,403);
globalThis.testUser={userId:'owner',email:'admin@test.invalid'};
assert.equal((await reviews.POST(req({...item,published:true}))).status,422);
assert.equal((await reviews.POST(req({...item,date:'2026-02-30'}))).status,422);
assert.equal((await reviews.POST(req({...item,sourceUrl:'javascript:alert(1)'}))).status,422);
assert.equal((await reviews.POST(req(item))).status,200);
assert.equal((await db.prepare('SELECT count(*) n FROM customer_reviews WHERE published=1').bind().first()).n,0);
assert.equal((await reviews.POST(req({...item,version:1,published:true,verified:true,consent:true}))).status,200);
assert.equal((await db.prepare('SELECT count(*) n FROM customer_reviews WHERE published=1').bind().first()).n,1);
assert.equal((await reviews.POST(req({...item,version:1}))).status,409);
assert.equal((await reviews.POST(req({...item,version:2}))).status,200);
assert.equal((await db.prepare('SELECT count(*) n FROM customer_reviews WHERE published=1').bind().first()).n,0);
const users=await import(module('app/api/admin/staff/route.ts'));
for(const role of ['sales','editor'])assert.equal((await users.POST(req({email:role+'@test.invalid',name:role,role,active:true,version:0}))).status,200);
globalThis.testUser={userId:'sales',email:'sales@test.invalid'};assert.equal((await reviews.GET()).status,403);assert.equal((await reviews.POST(req(item))).status,403);
globalThis.testUser={userId:'editor',email:'editor@test.invalid'};assert.equal((await reviews.GET()).status,200);
assert.equal((await reviews.POST(req({...item,id:crypto.randomUUID(),sortOrder:1}))).status,200);
const list=(await (await reviews.GET()).json()).reviews;assert.equal(list[0].sortOrder,1);assert.equal(list[1].version,3);
assert.equal((await reviews.POST(new Request('https://test.invalid/api/admin/reviews',{method:'POST',headers:{origin:'https://other.invalid'},body:JSON.stringify(item)}))).status,403);
console.log('PASS: reviews permission isolation, consent gate, dates, HTTPS links, drafts, publish/unpublish, stale writes, sorting, same-origin protection.');
