// PostgreSQL 版資料表結構（由原 drizzle/ SQLite migrations 轉換）。啟動時自動依序套用。
export const migrations: {version: string; sql: string}[] = [
  {version: "0000", sql: "CREATE TABLE IF NOT EXISTS bubu.audit_log (\n\tid text PRIMARY KEY NOT NULL,\n\tactor text NOT NULL,\n\taction text NOT NULL,\n\tentity_id text NOT NULL,\n\tdetail text NOT NULL,\n\tcreated_at text NOT NULL\n);\n\nCREATE TABLE IF NOT EXISTS bubu.inquiries (\n\tid text PRIMARY KEY NOT NULL,\n\trequest_key text NOT NULL,\n\tpayload_hash text NOT NULL,\n\towner_id text,\n\tname text NOT NULL,\n\tphone text NOT NULL,\n\tservices text NOT NULL,\n\tdetails text NOT NULL,\n\tstatus text DEFAULT '待聯繫' NOT NULL,\n\tnote text DEFAULT '' NOT NULL,\n\tversion integer DEFAULT 1 NOT NULL,\n\tconsent_version text NOT NULL,\n\tcreated_at text NOT NULL,\n\tupdated_at text NOT NULL,\n\trequest_fingerprint text NOT NULL\n);\n\nCREATE UNIQUE INDEX IF NOT EXISTS inquiries_request_key ON bubu.inquiries (request_key);\nCREATE INDEX IF NOT EXISTS inquiries_created_at ON bubu.inquiries (created_at);\nCREATE INDEX IF NOT EXISTS inquiries_fingerprint_created ON bubu.inquiries (request_fingerprint,created_at);\nCREATE INDEX IF NOT EXISTS inquiries_owner ON bubu.inquiries (owner_id);"},
  {version: "0001", sql: "CREATE TABLE IF NOT EXISTS bubu.case_studies (\n\tid text PRIMARY KEY NOT NULL,\n\tcontent text NOT NULL,\n\tpublished integer DEFAULT 0 NOT NULL,\n\tversion integer DEFAULT 1 NOT NULL,\n\tupdated_at text NOT NULL\n);\n\nCREATE INDEX IF NOT EXISTS case_studies_published_updated ON bubu.case_studies (published,updated_at);"},
  {version: "0002", sql: "CREATE TABLE IF NOT EXISTS bubu.payments (\n\ttrade_no text PRIMARY KEY NOT NULL,\n\tquote_id text NOT NULL,\n\tamount integer NOT NULL,\n\tmode text NOT NULL,\n\tmerchant_id text NOT NULL,\n\tstatus text DEFAULT 'pending' NOT NULL,\n\tfields text NOT NULL,\n\tgateway_trade_no text,\n\tresult_code text,\n\tpaid_at text,\n\tcreated_at text NOT NULL,\n\tupdated_at text NOT NULL\n);\n\nCREATE UNIQUE INDEX IF NOT EXISTS payments_quote ON bubu.payments (quote_id);\nCREATE TABLE IF NOT EXISTS bubu.quotes (\n\tid text PRIMARY KEY NOT NULL,\n\tinquiry_id text,\n\tcontent text NOT NULL,\n\ttotal integer NOT NULL,\n\tstatus text DEFAULT 'draft' NOT NULL,\n\tversion integer DEFAULT 1 NOT NULL,\n\ttoken text NOT NULL,\n\taccepted_at text,\n\tcreated_at text NOT NULL,\n\tupdated_at text NOT NULL\n);\n\nCREATE UNIQUE INDEX IF NOT EXISTS quotes_token ON bubu.quotes (token);\nCREATE INDEX IF NOT EXISTS quotes_inquiry ON bubu.quotes (inquiry_id);\nCREATE INDEX IF NOT EXISTS quotes_updated ON bubu.quotes (updated_at);"},
  {version: "0003", sql: "CREATE TABLE IF NOT EXISTS bubu.media_assets (\n\tid text PRIMARY KEY NOT NULL,\n\tmime text NOT NULL,\n\tsize integer NOT NULL,\n\tcreated_at text NOT NULL\n);\n\nCREATE TABLE IF NOT EXISTS bubu.site_photos (\n\tsource text PRIMARY KEY NOT NULL,\n\tasset_id text,\n\talt text DEFAULT '' NOT NULL,\n\tversion integer DEFAULT 1 NOT NULL,\n\tupdated_at text NOT NULL\n);"},
  {version: "0004", sql: "CREATE TABLE IF NOT EXISTS bubu.catalog_items (\n\tid text PRIMARY KEY NOT NULL,\n\tcontent text NOT NULL,\n\tversion integer DEFAULT 1 NOT NULL,\n\tupdated_at text NOT NULL\n);\n\nCREATE TABLE IF NOT EXISTS bubu.content_posts (\n\tid text PRIMARY KEY NOT NULL,\n\tkind text NOT NULL,\n\tdraft text NOT NULL,\n\tpublished_content text,\n\tversion integer DEFAULT 1 NOT NULL,\n\tupdated_at text NOT NULL\n);\n\nCREATE TABLE IF NOT EXISTS bubu.dispatch_outbox (\n\tid text PRIMARY KEY NOT NULL,\n\tquote_id text NOT NULL,\n\tpayload text NOT NULL,\n\tstatus text DEFAULT 'queued' NOT NULL,\n\tattempts integer DEFAULT 0 NOT NULL,\n\tlock_until text,\n\tlast_error text DEFAULT '' NOT NULL,\n\texternal_id text,\n\tcreated_at text NOT NULL,\n\tupdated_at text NOT NULL\n);\n\nCREATE UNIQUE INDEX IF NOT EXISTS dispatch_quote ON bubu.dispatch_outbox (quote_id);\nCREATE TABLE IF NOT EXISTS bubu.staff (\n\temail text PRIMARY KEY NOT NULL,\n\tname text NOT NULL,\n\trole text NOT NULL,\n\tactive integer DEFAULT 1 NOT NULL,\n\tversion integer DEFAULT 1 NOT NULL,\n\tupdated_at text NOT NULL\n);\n\nALTER TABLE bubu.inquiries ADD COLUMN IF NOT EXISTS assigned_to text;\nALTER TABLE bubu.quotes ADD COLUMN IF NOT EXISTS assigned_to text;"},
  {version: "0005", sql: "CREATE INDEX IF NOT EXISTS inquiries_assigned_created ON bubu.inquiries (assigned_to,created_at);\nCREATE INDEX IF NOT EXISTS quotes_assigned_updated ON bubu.quotes (assigned_to,updated_at);"},
  {version: "0006", sql: "CREATE TABLE IF NOT EXISTS bubu.customer_reviews (\n\tid text PRIMARY KEY NOT NULL,\n\tcontent text NOT NULL,\n\tpublished integer DEFAULT 0 NOT NULL,\n\tsort_order integer DEFAULT 0 NOT NULL,\n\tversion integer DEFAULT 1 NOT NULL,\n\tupdated_at text NOT NULL\n);\n\nCREATE INDEX IF NOT EXISTS reviews_published_order ON bubu.customer_reviews (published,sort_order);"},
  {version: "0007", sql: "CREATE TABLE IF NOT EXISTS bubu.media_blobs (\n\tid text PRIMARY KEY NOT NULL,\n\tmime text NOT NULL,\n\tdata bytea NOT NULL\n);"},
];
