import {ManagedImage} from '@/components/managed-image';
import {VisualIcon, type VisualKind} from '@/components/visual-explainer';
import {ArrowUpRight,ClipboardCheck,ShieldCheck,MessagesSquare,PackageCheck} from 'lucide-react';
import {qualityPoints,guides} from '@/lib/editorial';
import {publishedCases} from '@/lib/case-data';
import {CaseCard} from './case-card';
const icons=[ClipboardCheck,ShieldCheck,MessagesSquare,PackageCheck];
export function QualitySection(){return <section id="quality" className="quality-section"><div className="wrap"><div className="section-title"><div><span className="eyebrow">THE DETAILS MAKE THE DIFFERENCE</span><h2>值得放心的搬家，<br/>藏在每一個細節裡。</h2></div><p>好的服務，不只把物品搬到目的地。<br/>更是把事情說清楚，把需要照顧的地方先想好。</p></div><div className="quality-grid">{qualityPoints.map((p,i)=>{const Icon=icons[i];return <article key={p.n}><div className="quality-icon"><Icon size={27}/><span>{p.n}</span></div><h3>{p.title}</h3><p>{p.short}</p></article>})}</div><a className="text-link" href="/about#standards">了解步步的服務方式 <ArrowUpRight size={16}/></a></div></section>}
export async function CasesSection(){const {cases,unavailable}=await publishedCases();return <section className="section wrap" id="cases"><div className="section-title"><div><span className="eyebrow">MOVING STORIES</span><h2>每一個家，都有自己的故事。</h2></div><a href="/cases" className="section-link">服務案例 <ArrowUpRight size={18}/></a></div>{cases.length?<div className="case-grid">{cases.slice(0,3).map(c=><CaseCard key={c.id} item={c}/>)}</div>:<div className="case-intro"><div className="case-intro-photo"><ManagedImage src="/moving.jpg" alt="家具保護服務情境示意" loading="lazy"/><small>AI 服務情境示意，非實際案件照片</small></div><div className="case-intro-copy"><span className="eyebrow">從需求，到安心交付</span><h3>不只看搬了什麼，<br/>也看我們如何照顧。</h3><p>搬運動線怎麼安排？家具怎麼保護？打包與清潔如何接上？每一篇案例，都從客戶的需求說起。</p><div className="case-chapters"><span>01 需求與難點</span><span>02 處理與保護</span><span>03 交付與成果</span></div><p className="hint">{unavailable?'案例內容暫時無法載入，請稍後再試。':'實際服務紀錄將於整理並取得授權後陸續公開。'}</p><a href="/inquiry" className="text-link">聊聊你的搬家需求 ↗</a></div></div>}</section>}
export function AboutTeaser(){return <section className="about-teaser wrap"><div><span className="eyebrow">ABOUT BU BU</span><h2>用搬家的專注，<br/>照顧生活的轉換。</h2></div><div><ManagedImage className="about-art" src="/illustrations/journey.png" alt="打包、搬運到新家安頓的插畫" loading="lazy"/><p>打包、搬運、清潔，一起安排好。</p><a href="/about" className="text-link">更多關於步步 <ArrowUpRight size={16}/></a></div></section>}
export function GuidesSection(){return <section id="guides" className="section wrap"><div className="section-title"><div><span className="eyebrow">BEFORE YOU MOVE</span><h2>把準備做好，搬家更從容。</h2></div><p>整理我們最常需要與你確認的細節，<br/>從第一次詢價，就開始少一點擔心。</p></div><div className="guide-grid">{guides.map((g,i)=><a key={g.id} href={'/guides/'+g.id}><VisualIcon kind={(["calendar","package","quote"] as VisualKind[])[i]}/><div><span>{g.label}</span><small>0{i+1}</small></div><h3>{g.title}</h3><p>{g.summary}</p><span className="case-link">閱讀指南 <ArrowUpRight size={17}/></span></a>)}</div></section>}
