import {sqliteTable,text,integer,index,uniqueIndex} from 'drizzle-orm/sqlite-core';
export const inquiries=sqliteTable('inquiries',{
 id:text('id').primaryKey(),requestKey:text('request_key').notNull(),payloadHash:text('payload_hash').notNull(),ownerId:text('owner_id'),assignedTo:text('assigned_to'),name:text('name').notNull(),phone:text('phone').notNull(),services:text('services').notNull(),details:text('details').notNull(),status:text('status').notNull().default('待聯繫'),note:text('note').notNull().default(''),version:integer('version').notNull().default(1),consentVersion:text('consent_version').notNull(),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull(),requestFingerprint:text('request_fingerprint').notNull()
},t=>[uniqueIndex('inquiries_request_key').on(t.requestKey),index('inquiries_created_at').on(t.createdAt),index('inquiries_fingerprint_created').on(t.requestFingerprint,t.createdAt),index('inquiries_owner').on(t.ownerId),index('inquiries_assigned_created').on(t.assignedTo,t.createdAt)]);
export const auditLog=sqliteTable('audit_log',{id:text('id').primaryKey(),actor:text('actor').notNull(),action:text('action').notNull(),entityId:text('entity_id').notNull(),detail:text('detail').notNull(),createdAt:text('created_at').notNull()});
export const caseStudies=sqliteTable('case_studies',{id:text('id').primaryKey(),content:text('content').notNull(),published:integer('published').notNull().default(0),version:integer('version').notNull().default(1),updatedAt:text('updated_at').notNull()},t=>[index('case_studies_published_updated').on(t.published,t.updatedAt)]);

export const quotes=sqliteTable('quotes',{
 id:text('id').primaryKey(),inquiryId:text('inquiry_id'),assignedTo:text('assigned_to'),content:text('content').notNull(),total:integer('total').notNull(),status:text('status').notNull().default('draft'),version:integer('version').notNull().default(1),token:text('token').notNull(),acceptedAt:text('accepted_at'),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()
},t=>[uniqueIndex('quotes_token').on(t.token),index('quotes_inquiry').on(t.inquiryId),index('quotes_updated').on(t.updatedAt),index('quotes_assigned_updated').on(t.assignedTo,t.updatedAt)]);
export const payments=sqliteTable('payments',{
 tradeNo:text('trade_no').primaryKey(),quoteId:text('quote_id').notNull(),amount:integer('amount').notNull(),mode:text('mode').notNull(),merchantId:text('merchant_id').notNull(),status:text('status').notNull().default('pending'),fields:text('fields').notNull(),gatewayTradeNo:text('gateway_trade_no'),resultCode:text('result_code'),paidAt:text('paid_at'),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()
},t=>[uniqueIndex('payments_quote').on(t.quoteId)]);

export const mediaAssets=sqliteTable('media_assets',{id:text('id').primaryKey(),mime:text('mime').notNull(),size:integer('size').notNull(),createdAt:text('created_at').notNull()});
export const sitePhotos=sqliteTable('site_photos',{source:text('source').primaryKey(),assetId:text('asset_id'),alt:text('alt').notNull().default(''),version:integer('version').notNull().default(1),updatedAt:text('updated_at').notNull()});

export const staff=sqliteTable('staff',{email:text('email').primaryKey(),name:text('name').notNull(),role:text('role').notNull(),active:integer('active').notNull().default(1),version:integer('version').notNull().default(1),updatedAt:text('updated_at').notNull()});
export const catalogItems=sqliteTable('catalog_items',{id:text('id').primaryKey(),content:text('content').notNull(),version:integer('version').notNull().default(1),updatedAt:text('updated_at').notNull()});
export const contentPosts=sqliteTable('content_posts',{id:text('id').primaryKey(),kind:text('kind').notNull(),draft:text('draft').notNull(),publishedContent:text('published_content'),version:integer('version').notNull().default(1),updatedAt:text('updated_at').notNull()});
export const dispatchOutbox=sqliteTable('dispatch_outbox',{id:text('id').primaryKey(),quoteId:text('quote_id').notNull(),payload:text('payload').notNull(),status:text('status').notNull().default('queued'),attempts:integer('attempts').notNull().default(0),lockUntil:text('lock_until'),lastError:text('last_error').notNull().default(''),externalId:text('external_id'),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[uniqueIndex('dispatch_quote').on(t.quoteId)]);
export const customerReviews=sqliteTable('customer_reviews',{id:text('id').primaryKey(),content:text('content').notNull(),published:integer('published').notNull().default(0),sortOrder:integer('sort_order').notNull().default(0),version:integer('version').notNull().default(1),updatedAt:text('updated_at').notNull()},t=>[index('reviews_published_order').on(t.published,t.sortOrder)]);
